version: '3.8'

services:
  db:
    image: postgres:14
    container_name: offre_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@outlook.com
      PGADMIN_DEFAULT_PASSWORD: adminpasswrd
    ports:
      - "5050:80"
    depends_on:
      - db

  offre_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: elcer/offre-api:latest  # ✅ image tag explicite
    container_name: offre_api
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana-storage:
