apiVersion: v1
kind: Secret
metadata:
  name: offre-api-secret
  namespace: offreapi
type: Opaque
stringData:
  POSTGRES_USER: elcer
  POSTGRES_PASSWORD: clidshd
  POSTGRES_DB: prd
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  DATABASE_URL: postgresql+psycopg2://elcer:clidshd@postgres:5432/prd?sslmode=disable
  UPLOAD_FOLDER: uploads
  SECRET_KEY: 57cbf4842af83e15eef260e74cebe189fe4aacec9603a380ac29c23c0f923e46
